
// THIS FILE IS AUTOGENERATED WHEN PAGES ARE UPDATED
import { lazy } from "react";
import { RouteObject } from "react-router-dom";


import { UserGuard } from "app";



const App = lazy(() => import("./pages/App.tsx"));
const CardTest = lazy(() => import("./pages/CardTest.tsx"));
const CardiovascularRisk = lazy(() => import("./pages/CardiovascularRisk.tsx"));
const ExerciseDetail = lazy(() => import("./pages/ExerciseDetail.tsx"));
const ExerciseLibrary = lazy(() => import("./pages/ExerciseLibrary.tsx"));
const Login = lazy(() => import("./pages/Login.tsx"));
const Logout = lazy(() => import("./pages/Logout.tsx"));
const Profile = lazy(() => import("./pages/Profile.tsx"));
const ProgressTracker = lazy(() => import("./pages/ProgressTracker.tsx"));
const UserProfileSetup = lazy(() => import("./pages/UserProfileSetup.tsx"));

export const userRoutes: RouteObject[] = [



	{ path: "/", element: <App />},
	{ path: "/card-test", element: <UserGuard><CardTest /></UserGuard>},
	{ path: "/cardtest", element: <UserGuard><CardTest /></UserGuard>},
	{ path: "/cardiovascular-risk", element: <UserGuard><CardiovascularRisk /></UserGuard>},
	{ path: "/cardiovascularrisk", element: <UserGuard><CardiovascularRisk /></UserGuard>},
	{ path: "/exercise-detail", element: <UserGuard><ExerciseDetail /></UserGuard>},
	{ path: "/exercisedetail", element: <UserGuard><ExerciseDetail /></UserGuard>},
	{ path: "/exercise-library", element: <UserGuard><ExerciseLibrary /></UserGuard>},
	{ path: "/exerciselibrary", element: <UserGuard><ExerciseLibrary /></UserGuard>},
	{ path: "/login", element: <Login />},
	{ path: "/logout", element: <UserGuard><Logout /></UserGuard>},
	{ path: "/profile", element: <UserGuard><Profile /></UserGuard>},
	{ path: "/progress-tracker", element: <UserGuard><ProgressTracker /></UserGuard>},
	{ path: "/progresstracker", element: <UserGuard><ProgressTracker /></UserGuard>},
	{ path: "/user-profile-setup", element: <UserGuard><UserProfileSetup /></UserGuard>},
	{ path: "/userprofilesetup", element: <UserGuard><UserProfileSetup /></UserGuard>},

];
